# Generated by Django 3.2.5 on 2021-09-21 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, null=True, unique=True)),
                ('phone', models.CharField(max_length=255, null=True, unique=True)),
                ('name', models.CharField(default='Test', max_length=50)),
                ('user_type', models.CharField(default='ananymous', max_length=20)),
                ('scope', models.CharField(default='', max_length=500)),
                ('domain', models.CharField(default='', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_online', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Domains',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Domain Name')),
            ],
        ),
        migrations.CreateModel(
            name='FullLengthKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=500, unique=True)),
                ('full_answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GeneralKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=500, unique=True)),
                ('gen_answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GramaticalKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=250)),
                ('key_answer', models.TextField(default='')),
                ('weight', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=250, verbose_name='Service Name')),
                ('did', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bservice.domains', verbose_name='Linked Domain Name')),
            ],
        ),
        migrations.CreateModel(
            name='StaticKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=500, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=20, null=True)),
                ('region', models.CharField(max_length=20, null=True)),
                ('country', models.CharField(max_length=20, null=True)),
                ('zipcode', models.CharField(max_length=7, null=True)),
                ('asn', models.CharField(max_length=10, null=True)),
                ('ipaddr', models.GenericIPAddressField(null=True)),
                ('country_calling_code', models.CharField(max_length=5, null=True)),
                ('latitute', models.DecimalField(decimal_places=5, max_digits=10, null=True)),
                ('longitute', models.DecimalField(decimal_places=5, max_digits=10, null=True)),
                ('user_name', models.CharField(max_length=15, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Technologies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technology', models.CharField(max_length=250, verbose_name='Technology Name')),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bservice.services', verbose_name='Linked Service Name')),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.TextField()),
                ('time', models.TimeField(auto_now_add=True)),
                ('relevant', models.BooleanField()),
                ('is_read', models.BooleanField(default=False)),
                ('aid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bservice.keywords')),
                ('cid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bservice.categories')),
                ('did', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bservice.domains')),
                ('faid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bservice.fulllengthkeyword')),
                ('gaid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bservice.generalkeyword')),
                ('other', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='they_messaged', to=settings.AUTH_USER_MODEL)),
                ('sid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bservice.services')),
                ('tid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bservice.technologies')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='User_messaged', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='keywords',
            name='tid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bservice.technologies', verbose_name='Linked Technology Name'),
        ),
        migrations.AddField(
            model_name='categories',
            name='tid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bservice.technologies', verbose_name='Linked Technology Name'),
        ),
    ]
