from django.conf.urls import url
from django.urls import path
from rest_framework.authtoken import views
from django.conf import settings
from django.conf.urls.static import static

# from rest_framework.routers import SimpleRouter
from .views import (CategoryListCreateView, CategoryRetrieveUpdateDeleteView,
                    DomainListCreateView, DomainRetrieveUpdateDeleteView,
                    FullLengthKeywordListCreateView,
                    FullLengthKeywordRetrieveUpdateDeleteView,
                    GeneralKeywordListCreateView,
                    GeneralKeywordRetrieveUpdateDeleteView,
                    GramaticalKeywordListCreateView,
                    GramaticalKeywordRetrieveUpdateDeleteView,
                    KeywordListCreateView, KeywordRetrieveUpdateDeleteView,
                    MessageListCreateView, MessageRetrieveUpdateDeleteView,
                    ServiceListCreateView, ServiceRetrieveUpdateDeleteView,
                    StaticKeywordListCreateView,
                    StaticKeywordRetrieveUpdateDeleteView,
                    TechnologyListCreateView,
                    TechnologyRetrieveUpdateDeleteView, UserDeleteView,
                    UserInfoListCreateView, UserInfoRetrieveUpdateDeleteView,
                    UserListCreateView, UserLoginView, UserLogoutView, 
                    UserRetrieveUpdateDeleteView, desss_service_keywords,
                    get_services, get_weights, humaninteractionapiView, humaninteractionmessageupdate, keyword_list,adminloginstatuscode)

urlpatterns = [
    # path('all/', include(router.urls)),
    path('api-token-auth/', views.obtain_auth_token, name="token"),
    path('user/login/', UserLoginView.as_view(), name='user-login'),
    path('user/logout', UserLogoutView.as_view(), name='user-logout'),
    path('user/', UserListCreateView.as_view(), name='user-api'),
    path('userdelete/', UserDeleteView.as_view(), name='user-delete'),
    path('user/<int:pk>/', UserRetrieveUpdateDeleteView.as_view(), name='user-api'),
    path('userinfo/', UserInfoListCreateView.as_view(), name='userinfo-api'),
    path('userinfo/<int:pk>/', UserInfoRetrieveUpdateDeleteView.as_view(), name='userinfo-api'),
    path('keyword/', KeywordListCreateView.as_view(),  name='kcreate_api'),
    path('keyword/<int:pk>/', KeywordRetrieveUpdateDeleteView.as_view(),  name='kupdate-api'),
    path('domain/', DomainListCreateView.as_view(), name='dcreate_api'),
    path('domain/<int:pk>/', DomainRetrieveUpdateDeleteView.as_view(), name='dupdate_api'),
    path('service/', ServiceListCreateView.as_view(), name='screate_api'),
    path('service/<int:pk>/', ServiceRetrieveUpdateDeleteView.as_view(), name='supdate_api'),
    path('tech/', TechnologyListCreateView.as_view(), name='tcreate_api'),
    path('tech/<int:pk>/', TechnologyRetrieveUpdateDeleteView.as_view(), name='tupdate_api'),
    path('category/', CategoryListCreateView.as_view(), name='ccreate_api'),
    path('category/<int:pk>/', CategoryRetrieveUpdateDeleteView.as_view(), name='cupdate_api'),
    path('message/', MessageListCreateView.as_view(), name='mcreate_api'),
    path('message/<int:pk>/', MessageRetrieveUpdateDeleteView.as_view(), name='mupdate_api'),
    path('fulllenkeyword/', FullLengthKeywordListCreateView.as_view(),  name='kcreate_api'),
    path('fulllenkeyword/<int:pk>/',
        FullLengthKeywordRetrieveUpdateDeleteView.as_view(),  name='kcreate_api'),
    path('genkeyword/', GeneralKeywordListCreateView.as_view(),  name='kcreate_api'),
    path('genkeyword/<int:pk>/', GeneralKeywordRetrieveUpdateDeleteView.as_view(),
        name='kcreate_api'),
    path('statickeyword/', StaticKeywordListCreateView.as_view(),  name='kcreate_api'),
    path('statickeyword/<int:pk>/', StaticKeywordRetrieveUpdateDeleteView.as_view(),
        name='kcreate_api'),
    path('gramaticalkeyword/', GramaticalKeywordListCreateView.as_view(),  name='kcreate_api'),
    path('gramaticalkeyword/<int:pk>/', GramaticalKeywordRetrieveUpdateDeleteView.as_view(),
        name='kcreate_api'),
    path('allkeyword/', keyword_list),
    path('getweight/', get_weights),
    path('desss_keywords/', desss_service_keywords, name='desss-keywords'),
    path('search_services/', get_services, name='desss-services'),
	url(r'adminstatus/',adminloginstatuscode.as_view(),name = "admin status"),
    url(r'human/',humaninteractionapiView.as_view(),name = "HI-R"),
    url(r'human/<int:pk>/',humaninteractionmessageupdate.as_view(),name = "HI-R"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
